try conditional run

diff --git a/.github/workflows/pr-playwright.yaml b/.github/workflows/pr-playwright.yaml
--- a/.github/workflows/pr-playwright.yaml
+++ b/.github/workflows/pr-playwright.yaml
@@ -3,11 +3,43 @@ name: Playwright tests
 on:
   pull_request:
     branches: [main]
-  workflow_dispatch:
 
 jobs:
+  changes:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18
+      - name: Determine changes
+        env:
+          HEAD: ${{ github.event.pull_request.head.sha }}
+          BASE: ${{ github.event.pull_request.base.sha }}
+        run: |
+          root=$(pwd)
+          cd plugins
+
+          changed=()
+          for f in */; do
+            if git diff --name-only $BASE $HEAD | grep $f -q; then
+              if [[ ! -L "$f" && -f "$f/package.json" ]]; then
+                cd $f
+
+                if npm run | grep ui-test -q; then
+                  changed+=($f)
+                fi
+                cd $root/plugins
+              fi
+            fi
+          done
+
+          JSON="[$(echo ${changed[@]} | sed 's/ /,/g')]"
+          echo "plugins=$(echo $JSON)" >> $GITHUB_OUTPUT
   playwright:
     name: 'Playwright Tests'
+    needs: changes
+    if: needs.changes.outputs.plugins != '[]'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -19,9 +51,14 @@ jobs:
       - name: Install playwright
         run: yarn playwright install --with-deps chromium
       - name: Run tests
+        env:
+          PLUGINS: ${{needs.changes.outputs.plugins}}
         run: |
           root=$(pwd)
           cd packages/backend
+          readarray folders < <(echo $PLUGINS | sed 's/[][]//g' | sed 's/,/ /g')
+
+          echo ${folders[@]}
 
           # Start backend
           echo "Starting backend"
@@ -47,44 +84,39 @@ jobs:
 
           cd $root/plugins
 
-          # Look through all plugins
-          for f in */; do
-            if [[ ! -L "$f" && -f "$f/package.json" ]]; then
-              cd $f
-              
-              # Find plugins with UI tests
-              if npm run | grep ui-test -q; then
-                echo "Starting $f plugin"
-                tmpfile=$(mktemp)
+          # Launch suitable plugins with changes
+          for f in $folders; do
+            cd $f
 
-                # Start the plugin
-                yarn start >$tmpfile 2>&1 &
-                for attempt in $(seq 1 45); do
-                  sleep 1
-                  if grep -q "Error:" $tmpfile; then
-                  cat $tmpfile
-                  exit 1
-                  fi
-                  if grep -q "webpack compiled" $tmpfile; then
-                    echo "$f started"
-                    break
-                  fi
-                  if [[ attempt -eq 45 ]]; then
-                    echo "Failed to launch $f"
-                    cat $tmpfile
-                    exit 1
-                  fi
-                done
+            echo "Starting $f plugin"
+            tmpfile=$(mktemp)
 
-                # Run UI tests
-                yarn run ui-test
-                
-                # Kill the plugin
-                pid=$(lsof -i :3000 -Fp | grep p | sed s/p//)
-                kill -9 $pid && echo "$f shut down"
+            # Start the plugin
+            yarn start >$tmpfile 2>&1 &
+            for attempt in $(seq 1 45); do
+              sleep 1
+              if grep -q "Error:" $tmpfile; then
+              cat $tmpfile
+              exit 1
               fi
-              cd $root/plugins
-            fi
+              if grep -q "webpack compiled" $tmpfile; then
+                echo "$f started"
+                break
+              fi
+              if [[ attempt -eq 45 ]]; then
+                echo "Failed to launch $f"
+                cat $tmpfile
+                exit 1
+              fi
+            done
+
+            # Run UI tests
+            yarn run ui-test
+            
+            # Kill the plugin
+            pid=$(lsof -i :3000 -Fp | grep p | sed s/p//)
+            kill -9 $pid && echo "$f shut down"
+            cd $root/plugins
           done
 
           # Kill backend
