move script

diff --git a/.github/workflows/pr-playwright.yaml b/.github/workflows/pr-playwright.yaml
--- a/.github/workflows/pr-playwright.yaml
+++ b/.github/workflows/pr-playwright.yaml
@@ -19,7 +19,77 @@ jobs:
       - name: Install playwright
         run: yarn playwright install --with-deps chromium
       - name: Run tests
-        run: bash .github/actions/playwright/test-launch.sh
+        run: |
+          root=$(pwd)
+          cd packages/backend
+
+          # Start backend
+          echo "Starting backend"
+          logfile=$(mktemp)
+          yarn start >$logfile 2>&1 &
+
+          for attempt in $(seq 1 45); do
+            sleep 1
+            if grep -q "Error:" $logfile; then
+              cat $logfile
+              exit 1
+            fi
+            if grep -q "Listening on" $logfile; then
+              echo "Backend started"
+              break
+            fi
+            if [[ attempt -eq 45 ]]; then
+              echo "Failed to launch backend"
+              cat $logfile
+              exit 1
+            fi
+          done
+
+          cd $root/plugins
+
+          # Look through all plugins
+          for f in */; do
+            if [[ ! -L "$f" && -f "$f/package.json" ]]; then
+              cd $f
+              
+              # Find plugins with UI tests
+              if npm run | grep ui-test -q; then
+                echo "Starting $f plugin"
+                tmpfile=$(mktemp)
+
+                # Start the plugin
+                yarn start >$tmpfile 2>&1 &
+                for attempt in $(seq 1 45); do
+                  sleep 1
+                  if grep -q "Error:" $tmpfile; then
+                  cat $tmpfile
+                  exit 1
+                  fi
+                  if grep -q "webpack compiled" $tmpfile; then
+                    echo "$f started"
+                    break
+                  fi
+                  if [[ attempt -eq 45 ]]; then
+                    echo "Failed to launch $f"
+                    cat $tmpfile
+                    exit 1
+                  fi
+                done
+
+                # Run UI tests
+                yarn run ui-test
+                
+                # Kill the plugin
+                pid=$(lsof -i :3000 -Fp | grep p | sed s/p//)
+                kill -9 $pid && echo "$f shut down"
+              fi
+              cd $root/plugins
+            fi
+          done
+
+          # Kill backend
+          pid=$(lsof -i :7007 -Fp | grep p | sed s/p//)
+          kill -9 $pid && echo "Backend shut down"
       - uses: actions/upload-artifact@v3
         if: always()
         with:
